Bash/python tutorial/readme edits
Damien-Black/dnanexus-example-applets pull request #1
Opened 2017-08-08 23:39 UTC by slzarate

Made small edits to all of the README (and some of the dxapp.json) files in order to make them more legible and appropriately customer-facing.

2017-08-09 03:09 UTC, Damien-Black commented on Tutorials/bash/samtools_count/Readme.md
> +For bash scripts, inputs to a job execution become environment variables. The inputs from `our dxapp.json` file are formatted as shown below:
include our in code span: our `dxapp.json`

2017-08-09 04:14 UTC, Damien-Black requested changes
Thanks for reading the documentation! looks pretty clean, couple questions for you:

1. `subjobs` v. `sub-jobs`. I had the feeling the latter was correct; however, our [documentation](https://wiki.dnanexus.com/Job-Lifecycle) repeatedly uses the term `subjob`. Since this doc links to the wiki we should be consistent.
2. I use the term app(let) a lot, obvious reasons. Seeing the word became a tad annoying to read on a page. Did the usage of app(let) seem... excessive?

2017-08-09 04:14 UTC, Damien-Black commented on Tutorials/bash/samtools_count_git_sh/dxapp.json
> +      "help": "Output file with total reads as the first line."
Updating JSON help string +1

2017-08-09 04:14 UTC, Damien-Black commented on Tutorials/bash/samtools_count_para_chr_busyproc_sh/Readme.md
> +* `-x` prints commands as they are executed, which very useful for tracking the job's status or pinpointing the exact execution failure.
which is

2017-08-09 04:14 UTC, Damien-Black commented on Tutorials/bash/samtools_count_para_chr_busyproc_sh/Readme.md
> +The `*.bai` file was an optional job input. We check for a empty or unset `var` using the bash built-in test `[[ - z ${var}} ]]`. Then, we can download or create a `*.bai` index as needed.
Slick catch with the `[[ - z ${var}} ]]`. When you fixed it you added a space between the `-` and `z`:

`if [[ -z ${var}} ]]`

2017-08-09 04:14 UTC, Damien-Black commented on Tutorials/bash/samtools_count_para_chr_xargs_sh/Readme.md
> +This applet slices a BAM file by canonical chromosome then performs a parallelized `samtools view -c` using xargs. Type `man xargs` for general usage information.
OH MY GOD! You have no idea how long I went back and forth on _parallelized_ v. _parallel_. Doesn't parallelized just sound... wordy and wrong.

Keep whichever one you think is right.

2017-08-09 04:14 UTC, Damien-Black commented on Tutorials/bash/samtools_count_para_chr_xargs_sh/Readme.md
> +2.  Provide the DNAnexus link as a job's output using the function `dx-jobutil-add-output <output name>`
use script instead of function.  Just so users don't do a `declare -f dx-jobutil-add-output` and think something is wrong.

2017-08-09 21:41 UTC, slzarate commented on Tutorials/bash/samtools_count_para_chr_xargs_sh/Readme.md
> +This applet slices a BAM file by canonical chromosome then performs a parallelized `samtools view -c` using xargs. Type `man xargs` for general usage information.
"Parallel" is something that is, well, parallel. "Parallelized" is something that *has been made parallel*. See "straight" vs. "straightened".

2017-08-09 21:44 UTC, slzarate commented
1. Okay... I'll get to switching "sub-job" to "subjob" within the next day.
2. I agree that it looks odd on the page but don't know how to resolve this. Using "it" or referring to app(let)s more indirectly/infrequently may resolve this issue.

2017-08-10 23:42 UTC, slzarate commented
Can't tell how to search to make sure that's every occurrence of "sub-job", but I think it is.

2017-08-10 23:52 UTC, merged